baseURL: "https://romeodean.github.io/"
title: "Romeo Dean"
defaultContentLanguage: en
pagination:
  perPage: 10      # â† number of posts/papers per page
  pagerSize: 5     # â† how many page links (1 2 3 4 5) to show in the nav bar
theme: PaperMod

params:
  author: "Romeo Dean"
  homeInfoParams:
    Title: "Hi, I'm Romeo ðŸ‘‹"
    Content: >
      Brief bio goes here â€“ maybe your role, interests, or lab.
  socialIcons:
    - name: github
      url: "https://github.com/romeodean"
    - name: rss
      url: "index.xml"

menu:
  main:
    - name: Publications
      url: /publications/
      weight: 1
    - name: Blog
      url: /posts/
      weight: 2
    - name: CV
      url: /cv/
      weight: 3

